#!/bin/sh
#
# Copyright (c) Siemens AG, 2023
#
# Authors:
#  Tobias Schaffner <tobias.schaffner@siemens.com>
#
# SPDX-License-Identifier: MIT

set -ex

echo "osadl-rt-test-image" > /etc/hostname
echo "osadl preempt_rt evaluation image (login: root/root)" > /etc/issue
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

# isc-dhcp-server
systemctl enable dhclient.service

# ntpsec is started with high priority in newer debian versions
# this can lead to high latencies on unisolated cores.
if [ -w "/etc/default/ntpsec" ]; then
   sed -i 's|NTPD_OPTS="-g -N"|NTPD_OPTS="-g"|g' /etc/default/ntpsec
   sed -i 's|IGNORE_DHCP=""|IGNORE_DHCP="yes"|g' /etc/default/ntpsec
fi
