#!/bin/sh
#
# Copyright (c) Siemens AG, 2023
#
# Authors:
#  Tobias Schaffner <tobias.schaffner@siemens.com>
#
# SPDX-License-Identifier: MIT

set -e

echo "osadl-rt-test-image" > /etc/hostname
echo "osadl preempt_rt evaluation image (login: root/root)" > /etc/issue
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

# isc-dhcp-server
systemctl enable dhclient.service
